jobs:
  include:
    - stage: "node_js-10"
      name: "node_js-10"
      language: node_js
      sudo: false
      node_js:
        - 10
      cache:
        npm: false
      before_install:
        - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z ${encrypted_key} ] &&
          openssl aes-256-cbc -d -in secrets.js.enc -out test/resources/secrets.js -K $encrypted_key
          -iv $encrypted_iv -base64 || true'
      script:
        - npm run build
        - curl https://us-south.functions.appdomain.cloud/api/v1/web/e6b54af6-ab44-4149-a8e4-e906dcc58136/default/secadvstg-location-shift.json
        - echo "${FINDINGS_ENV}" | base64 -d >> findings_v1.env
        - echo "${NOTIFICATIONS_ENV}" | base64 -d >> notifications_v1.env
        # - echo "${CONFIGURATION_GOVERNANCE_ENV}" | base64 -d >> configuration_governance_v1.env
        - npm run test-unit-travis || travis_terminate 1
        - npm run test-integration-travis || travis_terminate 1
        - npm run check-packages
      after_success:
        - npm run report-coverage
    - stage: "node_js-12"
      name: "node_js-12"
      language: node_js
      sudo: false
      node_js:
        - 12
      cache:
        npm: false
      before_install:
        - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z ${encrypted_key} ] &&
          openssl aes-256-cbc -d -in secrets.js.enc -out test/resources/secrets.js -K $encrypted_key
          -iv $encrypted_iv -base64 || true'
      script:
        - npm run build
        - curl https://us-south.functions.appdomain.cloud/api/v1/web/e6b54af6-ab44-4149-a8e4-e906dcc58136/default/secadvstg-location-shift.json
        - echo "${FINDINGS_ENV}" | base64 -d >> findings_v1.env
        - echo "${NOTIFICATIONS_ENV}" | base64 -d >> notifications_v1.env
        # - echo "${CONFIGURATION_GOVERNANCE_ENV}" | base64 -d >> configuration_governance_v1.env
        - npm run test-unit-travis || travis_terminate 1
        - npm run test-integration-travis || travis_terminate 1
        - npm run check-packages
      after_success:
        - npm run report-coverage
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
            branch: main
            node: 12
            repo: ibm-cloud-security/scc-node-sdk